server:
  port: 8080
grpc:
  port: 6565
  service:
    user-service:
      host: localhost
      port: 6565
---

spring:
    profiles: development
server:
    port: 8864

---

spring:
    profiles: production
server:
    port: 8864
